### PR TITLE
Heroku [turnkey] deployment

### PR DESCRIPTION
**Pull request by nobane**
These changes make privly-flask deployable to heroku.

### CODE REVIEW

**Comment by smcgregor** [comment]
@foxichu I am cleaning up pull requests. Can you please review or close this one?

**Comment by foxichu** [comment]
I can confirm this pull request works and is ready to merge. To test, checkout this branch and follow these steps:

- Create a heroku account and install the heroku client tool
- $ heroku login
- $ heroku create myappname # enter a name here that will become myappname.herokuapps.com
- $ git push heroku heroku-deployment:master

The `heroku create` command will add a `heroku` remote to the local git repository. Whatever is pushed to that remote's master branch is deployed as the app. The git push should output a bunch of remote output as it sets up the python app and environment.

**Comment by foxichu** [comment]
+1

**Comment by smcgregor** [comment]
I assume [this](https://toolbelt.heroku.com/) is the Heroku Client tool.

**Comment by smcgregor** [comment]
I am getting:
    
    $ git push heroku heroku-deployment:master
    error: src refspec heroku-deployment does not match any.
    error: failed to push some refs to 'https://git.heroku.com/privlysean.git'

**Comment by smcgregor** [comment]
@foxichu Any ideas?

**Comment by spectralsun** [comment]
@smcgregor, yes that is the correct tool. It looks like your local repository doesn't have a heroku-deployment branch.

**Comment by smcgregor** [comment]
Updated per our out of band conversation. See https://privlysean.herokuapp.com/

Do I create a user account at this point? Maybe we should limit user accounts to the Heroku owner?

**Comment by spectralsun** [comment]
Yes, a user account needs to be created somehow. There is a create_user command in privly-flask's manage.py script, but I don't know if heroku has a way to run the manage.py script from their heroku CLI tool. I may need to create some sort of heroku plugin that adds the commands to the heroku CLI.

**Comment by spectralsun** [comment]
Hooray! We can indeed easily run the manage.py script from the heroku CLI. 

I had to update the manage.py script because it was using an outdated way of creating a user. There is a new commit to pull in on this branch and push out to the heroku instance. Then run the following commands to init the database and create a user:
```
$ heroku run python manage.py init_db
$ heroku run python manage.py create_user -e test@example.com -p password

**Comment by spectralsun** [comment]
The app will also need to have the config wired up to the correct domain and a real database. I think by doing this, it is using the sqlite database.

**Comment by smcgregor** [comment]
> The app will also need to have the config wired up to the correct domain and a real database. I think by doing this, it is using the sqlite database.

This is only the case if you want to have a custom domain, correct?

**Comment by spectralsun** [comment]
>>The app will also need to have the config wired up to the correct domain and a real database. I think by doing this, it is using the sqlite database.

> This is only the case if you want to have a custom domain, correct?

No, the app by the default config sets up for localhost:3000. A config.py file needs to be created that has the correct URL setting, which will be either the free *.herokuapps.com domain or a custom one if the user has that feature available. 

I'm thinking the easiest solution would be to create a manage.py command that creates a config file.

**Comment by smcgregor** [comment]
Command line management is probably good for this. Another option would be to provide shell prompts on initial installation.

**Pull request closed without merging**
